version: "3.7"

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app

  prod:
    build:
      context: .
      target: prod
    environment:
      DOCKER_HOST: tcp://prod_docker:2375
    cap_add:
      - SYS_ADMIN
    volumes:
      - /var/lib/docker/plugins:/var/lib/docker/plugins:ro
      - /mnt/docker-volumes:/mnt/docker-volumes:shared
    depends_on:
      - prod_docker

  prod_docker:
    image: tecnativa/docker-socket-proxy
    environment:
      PLUGINS: 1
      VOLUMES: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  starter:
    build:
      context: .
      dockerfile: Dockerfile.starter
    environment:
      DOCKER_HOST: tcp://starter_docker:2375
      MOUNTER_DOCKER_NETWORK: docker-volume-mounter_default
      MOUNTER_DOCKER_HOST: tcp://prod_docker:2375
      IMAGE: decentralize/docker-plugin-volume-mounter
    depends_on:
      - starter_docker
      - prod_docker

  starter_docker:
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      POST: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
