version: "3.7"

services:
  app:
    image: decentralize/docker-plugin-volume-mounter
    cap_add:
      - SYS_ADMIN
    privileged: true
    volumes:
      - /mnt/docker-volumes:/mnt/docker-volumes:shared
      - /var/lib/docker/plugins:/var/lib/docker/plugins:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
