version: "3.7"

services:
  starter:
    image: decentralize/docker-plugin-volume-mounter-starter
    environment:
      IMAGE: decentralize/docker-plugin-volume-mounter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
